# Generated by Django 3.2.7 on 2021-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Users_Model',
            fields=[
                ('User_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'SF_Users',
            },
        ),
    ]
