# Generated by Django 3.2.7 on 2021-09-16 13:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Forms_Model',
            fields=[
                ('Form_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Form_Name', models.CharField(default='Untitled', max_length=50)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
                ('Last_Opened', models.DateTimeField(auto_now=True)),
                ('Form_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.sf_users_model')),
            ],
            options={
                'db_table': 'SF_Forms',
            },
        ),
        migrations.CreateModel(
            name='SF_Question_Model',
            fields=[
                ('Question_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Form_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.sf_forms_model')),
            ],
            options={
                'db_table': 'SF_Question',
            },
        ),
    ]
