# Generated by Django 3.2.7 on 2021-09-16 14:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_sf_forms_model_sf_question_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Options_Model',
            fields=[
                ('Option_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Option', models.CharField(max_length=100)),
                ('Is_Correct', models.BooleanField(default=False)),
                ('Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'db_table': 'SF_Options',
            },
        ),
    ]
