# Generated by Django 3.2.7 on 2021-09-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_sf_options_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sf_question_model',
            name='Image_Height',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sf_question_model',
            name='Image_Width',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sf_question_model',
            name='Mark',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
