# Generated by Django 3.2.7 on 2021-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_sf_forms_model_form_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sf_forms_model',
            name='Form_UID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
