# Generated by Django 3.2.7 on 2021-09-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0006_alter_sf_forms_model_form_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sf_forms_model',
            name='Form_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SF_Users_Model',
        ),
    ]
