# Generated by Django 3.2.7 on 2021-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_auto_20210918_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sf_question_model',
            name='Question_Type',
            field=models.CharField(choices=[('Choices', 'Choices'), ('Multiple Choices', 'Multiple Choices'), ('True/False', 'True/False'), ('Date', 'Date'), ('Short Answer', 'Short Answer')], default=None, max_length=30),
            preserve_default=False,
        ),
    ]
