# Generated by Django 3.2.7 on 2021-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_sf_question_model_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Cloudinary_Bin_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Public_Id', models.CharField(max_length=200)),
            ],
        ),
    ]
