# Generated by Django 3.2.7 on 2021-09-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0010_sf_options_model_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Forms_Settings_Model',
            fields=[
                ('SF_Forms_Settings_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Is_Quiz', models.BooleanField(default=False)),
                ('Auto_Correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SF_Short_And_LongAnswer_Model',
            fields=[
                ('Short_And_LongAnswer_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Answer_key', models.TextField()),
            ],
            options={
                'db_table': 'SF_Short_And_LongAnswer',
            },
        ),
        migrations.AlterField(
            model_name='sf_question_model',
            name='Question',
            field=models.TextField(default='Untitled Question'),
        ),
        migrations.AlterField(
            model_name='sf_question_model',
            name='Question_Type',
            field=models.CharField(choices=[('Choices', 'Choices'), ('Multiple Choices', 'Multiple Choices'), ('True/False', 'True/False'), ('Date', 'Date'), ('Short Answer', 'Short Answer')], default='Choices', max_length=30),
        ),
        migrations.AddField(
            model_name='sf_forms_model',
            name='Form_Settings_Id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.sf_forms_settings_model'),
        ),
    ]
